databases:
  - name: afyalink-db
    plan: free

services:
  - type: web
    name: afyalink-backend
    env: python
    rootDir: afyalink_backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn afyalink_backend.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: afyalink-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: afyalink-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://afyalink-iota.vercel.app
