# Generated by Django 4.2.26 on 2026-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
