# Generated by Django 4.2.26 on 2026-03-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_patientprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="id_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="practitionerprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="practitionerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="core.facility",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="core.facility",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="core.facility",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescriptions",
                to="core.facility",
            ),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="message",
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name="reminder",
            name="type",
            field=models.CharField(
                choices=[
                    ("FOLLOW_UP", "Follow-up"),
                    ("REFILL", "Medication Refill"),
                    ("MONITOR", "Monitoring Check"),
                ],
                default="FOLLOW_UP",
                max_length=50,
            ),
        ),
    ]
