# Generated by Django 4.2.26 on 2026-03-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_patientprofile_id_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="duration_days",
            field=models.IntegerField(blank=True, help_text="0 = ongoing", null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("once_daily", "Once daily"),
                    ("twice_daily", "Twice daily"),
                    ("three_daily", "Three times daily"),
                    ("four_daily", "Four times daily"),
                    ("every_8h", "Every 8 hours"),
                    ("every_12h", "Every 12 hours"),
                    ("weekly", "Once a week"),
                    ("as_needed", "As needed (PRN)"),
                ],
                default="twice_daily",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="with_food",
            field=models.CharField(
                blank=True,
                choices=[
                    ("with", "With food"),
                    ("without", "Empty stomach"),
                    ("either", "Either way"),
                ],
                default="with",
                max_length=10,
            ),
        ),
    ]
